In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# show all columns in pandas dataframe
pd.set_option('display.max_columns', None)

In [4]:
dir = 'G:/.shortcut-targets-by-id/1a2KJDruB4ByO9oJKAZto52DF4dvwN3Y3/grain_and_milling/OCR_google_api/model_comparison'
df_haiku = pd.read_csv(f'{dir}/2013_haiku.csv')
df_sonnet = pd.read_csv(f'{dir}/2013_sonnet.csv')
display(df_haiku.head(2))
display(df_sonnet.head(2))

,img_name,elevator_type,company,annotations,mailing_address,address,city,state,zipcode,phone,fax,email,internet,representatives,cap_up,cap_fl,ld_cap,li,rec,ld,svc,rr,swc
0,2013_1_0.png,R,"ALABAMA FARMERS COOPERATIVE, INC.",Grain Division,NaN,"Hwy. 52 E., 103 Columbia State Docks",Columbia,AL,36319,(334) 696-8034,(334) 696-8063,NaN,www.alafarm.com,Manager: Larry Knighton,579000.0,NaN,NaN,St,NaN,NaN,NaN,NaN,NaN
1,2013_1_1.png,R,"ALABAMA FARMERS COOPERATIVE, INC.",Grain Division,NaN,800A Market St. N.E.,Decatur,AL,35601,(256) 308-1684,(256) 351-8424,NaN,www.alafarm.com,Manager: Bo Rouse,2331000.0,NaN,NaN,Fed,NaN,NaN,NaN,NaN,NaN

,img_name,elevator_type,company,annotations,mailing_address,address,city,state,zipcode,phone,fax,email,internet,representatives,cap_up,cap_fl,ld_cap,li,rec,ld,svc,rr,swc
0,2013_1_0.png,R,"ALABAMA FARMERS COOPERATIVE, INC.",Grain Division,NaN,"Hwy. 52 E., 103 Columbia State Docks",Columbia,AL,36319,(334) 696-8034,(334) 696-8063,NaN,www.alafarm.com,Manager: Larry Knighton,579000.0,NaN,NaN,St,NaN,NaN,NaN,NaN,NaN
1,2013_1_1.png,R,"ALABAMA FARMERS COOPERATIVE, INC.",Grain Division,NaN,800A Market St. N.E.,Decatur,AL,35601,(256) 308-1684,(256) 351-8424,NaN,www.alafarm.com,Manager: Bo Rouse,2331000.0,NaN,NaN,Fed,NaN,NaN,NaN,NaN,NaN

In [5]:
def get_basic_stats(df):
    nrows = df.shape[0]
    n_unique_imgs = df['img_name'].nunique()
    # number of img_name with more than 1 rows
    n_imgs_with_multiple_rows = df.groupby('img_name').size().gt(1).sum()
    # percentiles of cap_up
    percentiles = df['cap_up'].quantile([0.25, 0.5, 0.75]).to_dict()
    # number of missing values in cap_up
    n_missing_cap_up = df['cap_up'].isna().sum()
    # percentiles of cap_fl
    percentiles_cap_fl = df['cap_fl'].quantile([0.25, 0.5, 0.75]).to_dict()
    # number of missing values in cap_fl
    n_missing_cap_fl = df['cap_fl'].isna().sum()
    # number of li == Fed
    n_li_fed = (df['li'] == 'Fed').sum()
    # number of li == St
    n_li_st = (df['li'] == 'St').sum()
    # as dataframe
    stats_df = pd.DataFrame({
        'nrows': [nrows],
        'n_unique_imgs': [n_unique_imgs],
        'n_imgs_with_multiple_rows': [n_imgs_with_multiple_rows],
        'cap_up_25th_percentile': [percentiles[0.25]],
        'cap_up_50th_percentile': [percentiles[0.5]],
        'cap_up_75th_percentile': [percentiles[0.75]],
        'n_missing_cap_up': [n_missing_cap_up],
        'cap_fl_25th_percentile': [percentiles_cap_fl[0.25]],
        'cap_fl_50th_percentile': [percentiles_cap_fl[0.5]],
        'cap_fl_75th_percentile': [percentiles_cap_fl[0.75]],
        'n_missing_cap_fl': [n_missing_cap_fl],
        'n_li_fed': [n_li_fed],
        'n_li_st': [n_li_st]
    })
    return stats_df

In [6]:
df_haiku_stats = get_basic_stats(df_haiku)
df_sonnet_stats = get_basic_stats(df_sonnet)

# comparing side by side
comparison_df = pd.concat([df_haiku_stats, df_sonnet_stats], ignore_index=True)
comparison_df.index = ['Haiku', 'Sonnet']
display(comparison_df)

,nrows,n_unique_imgs,n_imgs_with_multiple_rows,cap_up_25th_percentile,cap_up_50th_percentile,cap_up_75th_percentile,n_missing_cap_up,cap_fl_25th_percentile,cap_fl_50th_percentile,cap_fl_75th_percentile,n_missing_cap_fl,n_li_fed,n_li_st
Haiku,926,914,11,880750.0,1741000.0,3241000.0,104,750000.0,1328000.0,2768725.75,658,511,243
Sonnet,904,904,0,879250.0,1746000.0,3241000.0,102,750000.0,1303000.0,2748879.00,637,498,236

In [7]:
# filtering haiku to img_name with a sinfle row
df_haiku_single_row = df_haiku.groupby('img_name').filter(lambda x: len(x) == 1)
display(df_haiku_single_row.head(2))

,img_name,elevator_type,company,annotations,mailing_address,address,city,state,zipcode,phone,fax,email,internet,representatives,cap_up,cap_fl,ld_cap,li,rec,ld,svc,rr,swc
0,2013_1_0.png,R,"ALABAMA FARMERS COOPERATIVE, INC.",Grain Division,NaN,"Hwy. 52 E., 103 Columbia State Docks",Columbia,AL,36319,(334) 696-8034,(334) 696-8063,NaN,www.alafarm.com,Manager: Larry Knighton,579000.0,NaN,NaN,St,NaN,NaN,NaN,NaN,NaN
1,2013_1_1.png,R,"ALABAMA FARMERS COOPERATIVE, INC.",Grain Division,NaN,800A Market St. N.E.,Decatur,AL,35601,(256) 308-1684,(256) 351-8424,NaN,www.alafarm.com,Manager: Bo Rouse,2331000.0,NaN,NaN,Fed,NaN,NaN,NaN,NaN,NaN

In [11]:
# combining for comparison
df_comb_sonnet = df_sonnet[['img_name','elevator_type','company','city','state','cap_up','cap_fl','li']].copy()
df_comb_haiku = df_haiku_single_row[['img_name','elevator_type','company','city','state','cap_up','cap_fl','li']].copy()
df_comb = pd.merge(df_comb_haiku, df_comb_sonnet, on='img_name', suffixes=('_haiku', '_sonnet'))

cols_to_compare = ['elevator_type', 'company', 'city', 'state', 'cap_up', 'cap_fl', 'li']
# sort cols side by side for easier visual comparison
cols_sorted = ['img_name']
for col in cols_to_compare:
    cols_sorted.append(f'{col}_haiku')
    cols_sorted.append(f'{col}_sonnet')
df_comb = df_comb[cols_sorted]
display(df_comb.head(2))

,img_name,elevator_type_haiku,elevator_type_sonnet,company_haiku,company_sonnet,city_haiku,city_sonnet,state_haiku,state_sonnet,cap_up_haiku,cap_up_sonnet,cap_fl_haiku,cap_fl_sonnet,li_haiku,li_sonnet
0,2013_1_0.png,R,R,"ALABAMA FARMERS COOPERATIVE, INC.","ALABAMA FARMERS COOPERATIVE, INC.",Columbia,Columbia,AL,AL,579000.0,579000.0,NaN,NaN,St,St
1,2013_1_1.png,R,R,"ALABAMA FARMERS COOPERATIVE, INC.","ALABAMA FARMERS COOPERATIVE, INC.",Decatur,Decatur,AL,AL,2331000.0,2331000.0,NaN,NaN,Fed,Fed

In [14]:

for col in cols_to_compare:
    haiku_col = f'{col}_haiku'
    sonnet_col = f'{col}_sonnet'
    df_comb[f'{col}_match'] = df_comb[haiku_col] == df_comb[sonnet_col]
    # if both are nan, consider it a match
    df_comb[f'{col}_match'] = df_comb[f'{col}_match'] | (df_comb[haiku_col].isna() & df_comb[sonnet_col].isna())

# summary of matches
match_summary = {}
for col in cols_to_compare:
    match_col = f'{col}_match'
    n_matches = df_comb[match_col].sum()
    n_total = len(df_comb)
    match_summary[col] = {
        'n_matches': n_matches,
        'n_total': n_total,
        'percent_match': n_matches / n_total * 100
    }
match_summary_df = pd.DataFrame(match_summary).T
display(match_summary_df)

               n_matches  n_total  percent_match
elevator_type      903.0    903.0     100.000000
company            900.0    903.0      99.667774
city               898.0    903.0      99.446290
state              903.0    903.0     100.000000
cap_up             902.0    903.0      99.889258
cap_fl             899.0    903.0      99.557032
li                 903.0    903.0     100.000000

In [16]:
# check cases where cap_up does not match
cap_up_mismatch = df_comb[~df_comb['cap_fl_match']]
display(cap_up_mismatch)

,img_name,elevator_type_haiku,elevator_type_sonnet,company_haiku,company_sonnet,city_haiku,city_sonnet,state_haiku,state_sonnet,cap_up_haiku,cap_up_sonnet,cap_fl_haiku,cap_fl_sonnet,li_haiku,li_sonnet,elevator_type_match,company_match,city_match,state_match,cap_up_match,cap_fl_match,li_match
197,2013_8_24.png,R,R,CONSOLIDATED GRAIN & BARGE CO.,CONSOLIDATED GRAIN & BARGE CO.,Naples,Naples,IL,IL,6826000.0,6826000.0,NaN,2010000.0,Fed; St,Fed; St,True,True,True,True,True,False,True
214,2013_9_14.png,S,S,MONMOUTH GRAIN & DRYER,MONMOUTH GRAIN & DRYER,Monmouth,Monmouth,IL,IL,675000.0,675000.0,NaN,405000.0,St,St,True,True,True,True,True,False,True
539,2013_23_22.png,T,T,"THE ANDERSONS, INC.","THE ANDERSONS, INC.",Lake Odessa,Lake Odessa,MI,MI,1600000.0,1600000.0,NaN,300000.0,St,St,True,True,True,True,True,False,True
559,2013_24_18.png,S,S,"MICHIGAN AGRICULTURAL COMMODITIES, INC.","MICHIGAN AGRICULTURAL COMMODITIES, INC.",Newaygo,Newaygo,MI,MI,2850000.0,2850000.0,NaN,920000.0,St,St,True,True,True,True,True,False,True